### ISSUE TITLE
Build broke after update from 5.0.0 to 5.1.0

### ISSUE THREAD

**Issue by Sijoma** [Nightapes/ngx-validators#72]
Hello all,

our build broke after updating from ngx-validators to 5.1.0. Did something change in the version update? 

We are using Angular/core 8.2.2.

import { ValidatorsModule } from 'ngx-validators';
                                    ~~~~~~~~~~~~~~~~
app/pages/landing/account/login/login.component.ts:8:33 - error TS2307: Cannot find module 'ngx-validators'.

import { EmailValidators } from 'ngx-validators';
                                  ~~~~~~~~~~~~~~~~
app/pages/landing/account/register/register.component.ts:5:36 - error TS2307: Cannot find module 'ngx-validators'.

import { PasswordValidators } from 'ngx-validators';
                                     ~~~~~~~~~~~~~~~~

**Comment by Nightapes** [comment]
Thanks for the feedback, you are right, the lib in version 5.1.0 is broken.
I'm working on a fix

**Comment by Nightapes** [comment]
@Sijoma can you please try version `v5.1.1`, 
Sorry for the inconvenience
